spring:
  application:
    name: server-app

  datasource:
    url: jdbc:mysql://localhost:5432/main
    username: postgres
    password: devtest
    driver-class-name: org.postgresql.Driver

    hikari:
      auto-commit: false