
spring:
  application:
    name: server-app

  primary-datasource:
    jdbc-url: jdbc:postgresql://localhost:5454/main
    username: postgres
    password: devtest
    driver-class-name: org.postgresql.Driver

  replica-datasource:
    jdbc-url: jdbc:postgresql://localhost:5455/main
    username: postgres
    password: devtest
    driver-class-name: org.postgresql.Driver

  grpc:
    server:
      reflection:
        enabled: true
      port: 9090