x-db: &db
  image: postgres:17
  environment:
    - POSTGRES_PASSWORD=devtest
    - POSTGRES_DB=main
  healthcheck:
    test: ["CMD", "pg_isready", "-U", "postgres"]

services:
  db_primary:
    <<: *db
    container_name: primary
    ports:
      - "5454:5432"
    entrypoint: /etc/postgresql/entrypoint.sh
    volumes:
      - ./docker/db_primary/entrypoint.sh:/etc/postgresql/entrypoint.sh
      - ./docker/db_primary/pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./docker/db_primary_data:/var/lib/postgresql/data
      - ./docker/db_primary/init.sh:/docker-entrypoint-initdb.d/init.sh

  db_read_replica:
    <<: *db
    container_name: read_replica
    ports:
      - "5455:5432"
    entrypoint: /etc/postgresql/entrypoint.sh
    volumes:
      - ./docker/db_read_replica_data:/var/lib/postgresql/data
      - ./docker/db_read_replica/entrypoint.sh:/etc/postgresql/entrypoint.sh
    depends_on:
      db_primary:
        condition: service_healthy

volumes:
  db_primary_data:
    driver: local
  db_read_replica_data:
    driver: local